### ISSUE TITLE
Unable to install packages using KJSPKG.

### ISSUE THREAD

**Issue by ut-64bit** [Modern-Modpacks/kjspkg#7] opened 2023-08-27 02:45 UTC
When I try to install soljs using KJSPKG, it says "Jei not found" and won't install!
If you need more information, please let me know!

Environment:.
Forge 1.19.2
Both JEI and AppleSkin are installed.
python3.10

I have not tried to install other packages yet.

**Comment by RealRainbuu** [comment] 2023-08-27 03:26
hm, yeah that is odd. I tried doing this with a base KJS jei and appleskin pack and I get this issue too. This might be a soljs issue, so I'd say report that there aswell.

**Comment by ut-64bit** [comment] 2023-08-27 03:38
OH... There is no issue tab on the SolJS github...

**Comment by Gcat101** [comment] 2023-08-27 07:48
> hm, yeah that is odd. I tried doing this with a base KJS jei and appleskin pack and I get this issue too. This might be a soljs issue, so I'd say report that there aswell.

I specifically disabled issues on all of the packages that are on my repos so I can centralize. No need to report it there.

**Comment by Gcat101** [comment] 2023-08-27 12:13
![image](https://github.com/Modern-Modpacks/kjspkg/assets/79367505/45d8f5fe-a634-445d-aa3b-31148c555aa0)

Can't seem to reproduce. What version of JEI are you using?

**Comment by Gcat101** [comment] 2023-08-27 12:15
I'll assign rainbuu at this since he was able to reproduce this

**Comment by ut-64bit** [comment] 2023-08-27 14:25
> ![image](https://user-images.githubusercontent.com/79367505/263527643-45d8f5fe-a634-445d-aa3b-31148c555aa0.png)
> 
> Can't seem to reproduce. What version of JEI are you using?

I am currently using jei-1.19.2-forge-11.6.0.1018.
And one thing I was wondering, is KubeJS6.1 supported?

**Comment by Gcat101** [comment] 2023-08-27 14:29
hm, jei-1.19.2-forge-11.6.0.1018 still works for me, I'm guessing this is an issue with the windows version of kjspkg. We'll look into it.

**Comment by Gcat101** [comment] 2023-08-27 17:54
![image](https://github.com/Modern-Modpacks/kjspkg/assets/79367505/e7fb6dbf-8b4c-4d55-8b33-ef5364f19a76)

aha, I am able to reproduce this in windows

**Comment by Gcat101** [comment] 2023-08-27 18:03
should be fixed, update kjspkg

**Closed** 2023-08-27 18:02 UTC

**Comment by dakiba** [comment] 2024-06-02 14:01
can we get a "warning" instant of a error, if a mod is missing? I use a another mod then Jei and by a another package I get the error `Mod "Lootjs" not found` but its installed

**Comment by Gcat101** [comment] 2024-06-02 14:03
> by a another package I get the error `Mod "Lootjs" not found` but its installed

that probably means it's a broken package, can you tell me which one so I can report this to the author/fix it?

**Comment by dakiba** [comment] 2024-06-02 14:03
https://kjspkglookup.modernmodpacks.site/p/?id=kubejs-lootbags

**Comment by dakiba** [comment] 2024-06-02 14:04
still I prefer warnings over errors. that kubejs scripts will for sure work in 1.20 too as example

**Comment by Gcat101** [comment] 2024-06-02 14:17
> https://kjspkglookup.modernmodpacks.site/p/?id=kubejs-lootbags

cannot replicate, which version of lootjs are you using?

![image](https://github.com/Modern-Modpacks/kjspkg/assets/79367505/a50d2eeb-dbc8-434f-ae33-c25e60987285)

**Comment by Gcat101** [comment] 2024-06-02 14:18
> still I prefer warnings over errors. that kubejs scripts will for sure work in 1.20 too as example

that differs on package-by-package basis, if you are completely sure that a package can work on another version, please tell the author about that or open up a pull request to the corresponding package repository
